site_name: quaternionic

repo_url: https://github.com/moble/quaternionic

plugins:
  - search
  - mkapi
  # - mktheapidocs:
  #     modules:
  #       quaternionic:
  #         section: api
  #         source_repo: "https://github.com/moble/quaternionic"

nav:
  - index.md
  - API: mkapi/api/quaternionic

theme:
  name: 'readthedocs'

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js

markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.arithmatex:
      generic: true
